.\"                                      Hey, EMACS: -*- nroff -*-

.TH URLSCAN 1 "October 26, 2015"

.SH NAME
urlscan \- browse the URLs in an email message from a terminal
.SH SYNOPSIS
\fBurlscan\fR [options] <
.I message

\fBurlscan\fR [options]
.I message

.SH DESCRIPTION
\fBurlscan\fR accepts a single email message on standard
input, then displays a terminal-based list of the URLs in the given
message.  Selecting a URL uses the Python webbrowser module to 
determine which browser to open. The \fBBROWSER\fR environment 
variable will be used if it is set.

\fBurlscan\fR is primarily intended to be used with the
.B mutt
(1) mailreader, but it should work well with any terminal-based mail
program.

\fBurlscan\fR is similar to \fBurlview\fR(1), but has the following
additional features:

\fB1.\fR Support for more message encodings, such as quoted-printable
and base64.

\fB2.\fR Extraction and display of the context surrounding each URL.

.SH OPTIONS
.TP
.B \-c, \-\-compact
Display a simple list of the extracted URLs, instead of showing the
context of each URL.
.TP
.B \-n, \-\-no-browser
Disables the selection interface and print the links to standard output.
Useful for scripting (implies \fB\-\-compact\fR).

.SH MUTT INTEGRATION

To integrate urlscan with mutt, include the following two commands in
\fB~/.muttrc\fR:


.ad l
macro index,pager \\cb "<pipe-message> urlscan<Enter>" "call urlscan to extract URLs out of a message"

macro attach,compose \\cb "<pipe-entry> urlscan<Enter>" "call urlscan to extract URLs out of a message"
.ad b


Once these lines are in your mutt configuration file, pressing
Control-b will allow you to browse and open the URLs in the currently
selected message.

.SH SEE ALSO
\fI/usr/share/doc/urlscan/README\fR,
\fBurlview\fR(1),
\fBmutt\fR(1)

.SH AUTHOR
This manual page was written by Daniel Burrows <dburrows@debian.org> and Scott Hansen <firecat4153@gmail.com>
